const ImgImAMother = [
  {
    url: require(`./Embarazo0.png`),
    texTop: "Síntomas del embarazo",
    name: "¿Qué es el edema gestacional?",
    text: "El edema gestacional es una de las afecciones que ocurren con mayor frecuencia durante el embarazo. De hecho, la mayoría de las futuras mamás experimentan hinchazón en diferentes partes del cuerpo. A continuación, te contamos todo al respecto.",
    id: 0,
    link: "#",
  },
  {
    url: require(`./Embarazo1.png`),
    texTop: "Síntomas del embarazo",
    name: "¿Se puede comer mortadela en el embarazo?",
    text: "La mortadela es un embutido frecuente en muchas dietas. A pesar de que su calidad a nivel nutricional no es buena, cuenta con unas características organolépticas que agradan a muchos. Ahora bien, te vamos a contar si en el embarazo se puede comer mortadela o conviene suprimirla de la pauta, ya que hay muchos embutidos que deben ser restringidos en esta etapa.",
    id: 1,
    link: "#",
  },
  {
    url: require(`./Embarazo2.png`),
    texTop: "Síntomas del embarazo",
    name: "¿Se puede tomar soja en el embarazo?",
    text: "La soja es un alimento muy aconsejado para favorecer el estado de salud en las mujeres. Contiene en su interior una serie de compuestos conocidos como isoflavonas, que pueden optimizar la producción hormonal y reducir la sintomatología asociada a la menopausia. Ahora bien, te vamos a contar si se puede tomar soja en el embarazo o si debe restringirse en esta etapa.",
    id: 2,
    link: "#",
  },
  {
    url: require(`./Embarazo3.png`),
    texTop: "Síntomas del embarazo",
    name: "Manos hinchadas en el embarazo: causas y consejos",
    text: "Si bien lo más habitual es el edema de las piernas, algunas mujeres pueden notar sus manos hinchadas durante el embarazo. De hecho, son molestias comunes que comienzan a presentarse de forma más evidente en el último trimestre de la gestación.",
    id: 3,
    link: "#",
  },
  {
    url: require(`./Embarazo4.png`),
    texTop: "Síntomas del embarazo",
    name: "¿Se puede tomar soja en el embarazo?",
    text: "La soja es un alimento muy aconsejado para favorecer el estado de salud en las mujeres. Contiene en su interior una serie de compuestos conocidos como isoflavonas, que pueden optimizar la producción hormonal y reducir la sintomatología asociada a la menopausia. Ahora bien, te vamos a contar si se puede tomar soja en el embarazo o si debe restringirse en esta etapa.",
    id: 4,
    link: "#",
  },
  {
    url: require(`./Embarazo5.png`),
    texTop: "Síntomas del embarazo",
    name: "Barriga dura en el embarazo: ¿qué significa?",
    text: "El embarazo es una etapa en la que se experimentan diferentes sensaciones, desde sentir las primeras pataditas del bebé hasta notar la barriga dura en ciertas ocasiones. Especialmente, hacia el final del embarazo. Pero, ¿a qué se debe esto?",
    id: 5,
    link: "#",
  },
  {
    url: require(`./Embarazo6.png`),
    texTop: "Síntomas del embarazo",
    name: "Pecas en el embarazo: lo que debes saber",
    text: "La aparición de pecas en el embarazo es una de las manifestaciones más habituales de esta etapa, ya que se asocia a los cambios hormonales gestacionales. De hecho, más del 90 % de las mujeres presentan cambios importantes y complejos en su piel, que pueden impactar en su vida cotidiana.",
    id: 6,
    link: "#",
  },
  {
    url: require(`./Embarazo7.png`),
    texTop: "Síntomas del embarazo",
    name: "¿Se puede comer foie gras en el embarazo?",
    text: "El foie grass es un producto que se elabora a partir de las grasas de los animales, generalmente del pato o de la oca. Si bien se trata de un comestible nutritivo, durante ciertas etapas de la vida hay que restringir su ingesta, pues aumenta el riesgo microbiológico. Hoy te vamos a contar si el embarazo es uno de esos momentos en los que vale excluirlo de la dieta.",
    id: 7,
    link: "#",
  },
  {
    url: require(`./Embarazo8.png`),
    texTop: "Síntomas del embarazo",
    name: "¿Qué son los calambres de implantación?",
    text: "Las primeras semanas de embarazo suelen acompañarse de algunos síntomas un tanto extraños, como los calambres de implantación. Estas molestias abdominales se perciben como leves puntadas en el bajo vientre, que se asemejan a los dolores menstruales. Pero que en caso de coincidir con un atraso, pueden sugerir una gestación en curso.",
    id: 8,
    link: "#",
  },
];

export default ImgImAMother;
